language: php

php:
  - 5.6

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - cp app/phpunit.xml.dist app/phpunit.xml
  - composer self-update
  - composer install

script:
  - php phpunit -c app --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover