app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
       _locale: %app.locales%
    defaults:
        _locale: %locale%

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

logout:
    path: /logout
