<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param $comments_count
     * @return array
     */
    public function findLatestComments($comments_count)
    {
        return $this->createQueryBuilder('c')
            ->select('c, a')
            ->join('c.article', 'a')
            ->orderBy('c.createdAt', 'DESC')
            ->setFirstResult(0)
            ->setMaxResults($comments_count)
            ->getQuery()
            ->getResult();
    }
}
